export const INPUT_USER_REQUEST = 'INPUT_USER_REQUEST';
export const USER_LOGOUT = 'USER_LOGOUT';
export const INVALID_USER = 'INVALID_USER';

export const LOAD_USERS_START = 'LOAD_USERS_START';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_ERROR = 'LOAD_USERS_START';
