export const LOAD_ASSIGNMENTS_START = 'LOAD_ASSIGNMENTS_START';
export const LOAD_ASSIGNMENTS_SUCCESS = 'LOAD_ASSIGNMENTS_SUCCESS';
export const LOAD_ASSIGNMENTS_ERROR = 'LOAD_ASSIGNMENTS_START';

export const CREATE_ASSIGNMENT_START = 'CREATE_ASSIGNMENT_START';
export const CREATE_ASSIGNMENT_SUCCESS = 'CREATE_ASSIGNMENT_SUCCESS';
export const CREATE_ASSIGNMENT_ERROR = 'CREATE_ASSIGNMENT_ERROR';

export const DELETE_ASSIGNMENT_START = 'DELETE_ASSIGNMENT_START';
export const DELETE_ASSIGNMENT_SUCCESS = 'DELETE_ASSIGNMENT_SUCCESS';
export const DELETE_ASSIGNMENT_ERROR = 'DELETE_ASSIGNMENT_ERROR';

export const UPDATE_ASSIGNMENT_START = 'UPDATE_ASSIGNMENT_START';
export const UPDATE_ASSIGNMENT_SUCCESS = 'UPDATE_ASSIGNMENT_SUCCESS';
export const UPDATE_ASSIGNMENT_ERROR = 'UPDATE_ASSIGNMENT_ERROR';
